---
# ArmorEffect by refaltor
# need support : ! Refaltor#1000 on Discord
# Infinite config, infinite effect

317:
  effect:
    1:
      niveau: 1
      visible: false



314:
  effect:
    16:
      niveau: 1
      visible: false
...